spring:
  config:
    activate:
      on-profile: local

  jpa:
    show-sql: true

  devtools:
    restart:
      additional-exclude: db/migration/**,db/migration/*.sql,db/migration/*.tmp

caisora:
  seguranca:
    jwt:
      segredo: segredo-local-caisora-com-tamanho-suficiente-para-hmac-256
      expiracao-segundos: 3600

logging:
  level:
    br.com.caisora: DEBUG
